#cloud-config
# VibeStack Coolify with DNS-First Approach
# Fixes timing issues with DNS resolution during package installation

hostname: vibestack-coolify
timezone: UTC

# DISABLE automatic package management - we'll do this manually after DNS is fixed
package_update: false
package_upgrade: false
package_reboot_if_required: false

# Don't install packages automatically - DNS might not work yet
# packages: []

# DNS fix happens FIRST in bootcmd (early boot phase)
bootcmd:
  - echo "nameserver 1.1.1.1" > /etc/resolv.conf
  - echo "nameserver 1.0.0.1" >> /etc/resolv.conf
  - echo "nameserver 8.8.8.8" >> /etc/resolv.conf
  - echo "nameserver 8.8.4.4" >> /etc/resolv.conf
  - echo "DNS fixed in bootcmd" >> /var/log/vibestack-dns.log

write_files:
  # Backup DNS config
  - content: |
      nameserver 1.1.1.1
      nameserver 1.0.0.1
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    path: /etc/resolv.conf.vibestack
    permissions: '0644'

  # Environment file for Cloudflare configuration
  - content: |
%{ for var in cloudflare_env_vars ~}
      ${var}
%{ endfor ~}
    path: /opt/vibestack-ansible/.env
    permissions: '0644'

ssh_authorized_keys:
%{ for key in split("\n", ssh_authorized_keys) ~}
%{ if trimspace(key) != "" ~}
  - ${trimspace(key)}
%{ endif ~}
%{ endfor ~}

ssh_pwauth: false

# All package installation happens AFTER DNS is working
runcmd:
  # Ensure DNS is working
  - cp /etc/resolv.conf.vibestack /etc/resolv.conf
  - echo "Starting runcmd with DNS fix" >> /var/log/vibestack-setup.log

  # Test DNS resolution before proceeding
  - timeout 30 bash -c 'until nslookup ubuntu.com; do echo "Waiting for DNS..." >> /var/log/vibestack-setup.log; sleep 2; done'

  # Now safely update packages with working DNS
  - apt-get update || (sleep 10 && apt-get update)
  - apt-get install -y python3-pip git curl wget unzip software-properties-common resolvconf jq || (sleep 10 && apt-get install -y python3-pip git curl wget unzip software-properties-common resolvconf jq --fix-missing)

  # Create ansible directory
  - mkdir -p /opt/vibestack-ansible

  # Download the playbook (with retry logic)
  - timeout 60 wget -O /tmp/complete-setup.yml https://raw.githubusercontent.com/evolv3ai/oci-cloudnative/main/coolify-complete-setup.yml || (sleep 10 && timeout 60 wget -O /tmp/complete-setup.yml https://raw.githubusercontent.com/evolv3ai/oci-cloudnative/main/coolify-complete-setup.yml)
  - cp /tmp/complete-setup.yml /opt/vibestack-ansible/complete-setup.yml

  # Install pip and ansible with proper paths and retries
  - python3 -m pip install --upgrade pip || (sleep 5 && python3 -m pip install --upgrade pip)
  - sleep 5
  - pip3 install ansible docker || (sleep 5 && pip3 install ansible docker)
  - sleep 5

  # Install ansible collections with explicit paths and retries
  - /home/ubuntu/.local/bin/ansible-galaxy collection install community.general --force || /usr/local/bin/ansible-galaxy collection install community.general --force
  - /home/ubuntu/.local/bin/ansible-galaxy collection install community.docker --force || /usr/local/bin/ansible-galaxy collection install community.docker --force
  - /home/ubuntu/.local/bin/ansible-galaxy collection install ansible.posix --force || /usr/local/bin/ansible-galaxy collection install ansible.posix --force

  # Set proper permissions
  - chown -R ubuntu:ubuntu /opt/vibestack-ansible
  - chmod +x /opt/vibestack-ansible/complete-setup.yml

  # Run the automation playbook with proper path detection
  - cd /opt/vibestack-ansible && (/home/ubuntu/.local/bin/ansible-playbook complete-setup.yml || /usr/local/bin/ansible-playbook complete-setup.yml)

  # Log completion
  - echo "VibeStack Coolify setup completed at $(date)" >> /var/log/vibestack-setup.log

final_message: "VibeStack Coolify setup completed. Check /var/log/vibestack-setup.log for details."