#cloud-config
# VibeStack Coolify Cloud-Init Configuration
# Includes: DNS fixes, Cloudflare tunnel support, proper timing, and error handling

hostname: vibestack-coolify
timezone: UTC

# DISABLE automatic package management - we control timing for DNS
package_update: false
package_upgrade: false
package_reboot_if_required: false

# DNS fix happens FIRST in bootcmd (early boot phase)
bootcmd:
  - echo "nameserver 1.1.1.1" > /etc/resolv.conf
  - echo "nameserver 1.0.0.1" >> /etc/resolv.conf
  - echo "nameserver 8.8.8.8" >> /etc/resolv.conf
  - echo "nameserver 8.8.4.4" >> /etc/resolv.conf
  - echo "DNS configured at $(date)" >> /var/log/vibestack-dns.log

write_files:
  # Backup DNS config
  - content: |
      nameserver 1.1.1.1
      nameserver 1.0.0.1
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    path: /etc/resolv.conf.vibestack
    permissions: '0644'

  # Environment file for Cloudflare configuration
  - content: |
%{ for var in cloudflare_env_vars ~}
      ${var}
%{ endfor ~}
    path: /opt/vibestack-ansible/.env
    permissions: '0644'

%{ if setup_custom_ssl ~}
  # SSL Certificate Files
  - content: |
      ${ssl_cert_b64}
    path: /opt/vibestack-ansible/ssl-cert.b64
    permissions: '0600'
    owner: root:root
    encoding: plain

  - content: |
      ${ssl_key_b64}
    path: /opt/vibestack-ansible/ssl-key.b64
    permissions: '0600'
    owner: root:root
    encoding: plain

%{ if ssl_chain_b64 != "" ~}
  - content: |
      ${ssl_chain_b64}
    path: /opt/vibestack-ansible/ssl-chain.b64
    permissions: '0600'
    owner: root:root
    encoding: plain
%{ endif ~}

  - content: |
      SSL_ENABLED=true
      SSL_DOMAIN=${ssl_domain}
    path: /opt/vibestack-ansible/ssl-config.env
    permissions: '0644'
%{ endif ~}

ssh_authorized_keys:
%{ for key in split("\n", ssh_authorized_keys) ~}
%{ if trimspace(key) != "" ~}
  - ${trimspace(key)}
%{ endif ~}
%{ endfor ~}

ssh_pwauth: false

# All package installation happens AFTER DNS is working
runcmd:
  # Ensure DNS is working
  - cp /etc/resolv.conf.vibestack /etc/resolv.conf
  - echo "Starting VibeStack setup at $(date)" >> /var/log/vibestack-setup.log

  # Test DNS resolution before proceeding
  - timeout 30 bash -c 'until nslookup ubuntu.com; do echo "Waiting for DNS..." >> /var/log/vibestack-setup.log; sleep 2; done'

  # Now safely update packages with working DNS (with retries)
  - apt-get update || (sleep 10 && apt-get update)
  - apt-get install -y python3-pip git curl wget unzip software-properties-common resolvconf jq || (sleep 10 && apt-get install -y python3-pip git curl wget unzip software-properties-common resolvconf jq --fix-missing)

  # Create ansible directory
  - mkdir -p /opt/vibestack-ansible

  # Download the latest playbook from GitHub (with retry)
  - timeout 60 wget -O /tmp/complete-setup.yml https://raw.githubusercontent.com/evolv3ai/oci-cloudnative/main/coolify-complete-setup.yml || (sleep 10 && timeout 60 wget -O /tmp/complete-setup.yml https://raw.githubusercontent.com/evolv3ai/oci-cloudnative/main/coolify-complete-setup.yml)
  - cp /tmp/complete-setup.yml /opt/vibestack-ansible/complete-setup.yml

  # Install pip and ansible with proper paths and retries
  - python3 -m pip install --upgrade pip || (sleep 5 && python3 -m pip install --upgrade pip)
  - sleep 5
  - pip3 install ansible docker || (sleep 5 && pip3 install ansible docker)
  - sleep 5

  # Install ansible collections (try both possible paths)
  - /home/ubuntu/.local/bin/ansible-galaxy collection install community.general --force || /usr/local/bin/ansible-galaxy collection install community.general --force
  - /home/ubuntu/.local/bin/ansible-galaxy collection install community.docker --force || /usr/local/bin/ansible-galaxy collection install community.docker --force
  - /home/ubuntu/.local/bin/ansible-galaxy collection install ansible.posix --force || /usr/local/bin/ansible-galaxy collection install ansible.posix --force

  # Set proper permissions
  - chown -R ubuntu:ubuntu /opt/vibestack-ansible

%{ if setup_custom_ssl ~}
  # Process SSL certificates if provided
  - |
    if [ -f /opt/vibestack-ansible/ssl-cert.b64 ]; then
      echo "Processing SSL certificates..." >> /var/log/vibestack-setup.log
      # Decode certificates
      base64 -d /opt/vibestack-ansible/ssl-cert.b64 > /opt/vibestack-ansible/ssl.crt
      base64 -d /opt/vibestack-ansible/ssl-key.b64 > /opt/vibestack-ansible/ssl.key
      if [ -f /opt/vibestack-ansible/ssl-chain.b64 ]; then
        base64 -d /opt/vibestack-ansible/ssl-chain.b64 > /opt/vibestack-ansible/ssl-chain.crt
      fi
      # Set proper permissions
      chmod 644 /opt/vibestack-ansible/ssl.crt
      chmod 600 /opt/vibestack-ansible/ssl.key
      [ -f /opt/vibestack-ansible/ssl-chain.crt ] && chmod 644 /opt/vibestack-ansible/ssl-chain.crt
      # Clean up base64 files
      rm -f /opt/vibestack-ansible/*.b64
      echo "SSL certificates processed successfully" >> /var/log/vibestack-setup.log
    fi
%{ endif ~}

  # Run the automation playbook (try both paths)
  - cd /opt/vibestack-ansible && (/home/ubuntu/.local/bin/ansible-playbook complete-setup.yml || /usr/local/bin/ansible-playbook complete-setup.yml)

  # Log completion
  - echo "VibeStack Coolify setup completed at $(date)" >> /var/log/vibestack-setup.log

final_message: "VibeStack Coolify setup completed. Check /var/log/vibestack-setup.log for details."