#cloud-config
# VibeStack Coolify with Optional Cloudflare Tunnel
# Cloud-init configuration for automated deployment

hostname: vibestack-coolify
timezone: UTC
package_update: true
package_upgrade: true
package_reboot_if_required: false

packages:
  - python3
  - python3-pip
  - git
  - curl
  - wget
  - unzip
  - software-properties-common
  - resolvconf
  - jq

write_files:
  - content: |
      nameserver 1.1.1.1
      nameserver 1.0.0.1
      nameserver 8.8.8.8
      nameserver 8.8.4.4
    path: /etc/resolv.conf.vibestack
    permissions: '0644'
  - content: |
%{ for var in cloudflare_env_vars ~}
      ${var}
%{ endfor ~}
    path: /opt/vibestack-ansible/.env
    permissions: '0644'

ssh_authorized_keys:
%{ for key in split("\n", ssh_authorized_keys) ~}
%{ if trimspace(key) != "" ~}
  - ${trimspace(key)}
%{ endif ~}
%{ endfor ~}

ssh_pwauth: false

bootcmd:
  - cp /etc/resolv.conf.vibestack /etc/resolv.conf

runcmd:
  - cp /etc/resolv.conf.vibestack /etc/resolv.conf
  - mkdir -p /opt/vibestack-ansible
  - wget -O /tmp/complete-setup.yml https://raw.githubusercontent.com/evolv3ai/oci-cloudnative/main/coolify-complete-setup.yml
  - cp /tmp/complete-setup.yml /opt/vibestack-ansible/complete-setup.yml
  - python3 -m pip install --upgrade pip
  - sleep 5
  - pip3 install ansible
  - sleep 5
  - pip3 install docker
  - sleep 5
  - /usr/local/bin/ansible-galaxy collection install community.general --force
  - /usr/local/bin/ansible-galaxy collection install community.docker --force
  - /usr/local/bin/ansible-galaxy collection install ansible.posix --force
  - chown -R ubuntu:ubuntu /opt/vibestack-ansible
  - chmod +x /opt/vibestack-ansible/complete-setup.yml
  - cd /opt/vibestack-ansible && ansible-playbook complete-setup.yml
  - echo "VibeStack Coolify setup completed at $(date)" >> /var/log/vibestack-setup.log

final_message: "VibeStack Coolify setup completed. Check /var/log/vibestack-setup.log for details."